version: '3.8'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra1:/var/lib/cassandra
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-net
    ports:
      - "9043:9042"
    volumes:
      - ./data/cassandra2:/var/lib/cassandra
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-net
    ports:
      - "9044:9042"
    volumes:
      - ./data/cassandra3:/var/lib/cassandra
networks:
  cassandra-net:
    driver: bridge
